[aws]
region = "us-east-1"
access_key_id = "xxx" # update with your Access Key ID
secret_access_key = "xxx" # update with your Secret Access Key
sns_arn = "arn:aws:sns:us-east-1:xxx:kask-keg-event" # update with your SNS ARN
heartbeat_interval = "5s"

[arduino]
serial_port = "/dev/ttys001"
baud_rate = 115200
pin_to_tap = { 4 = 1, 5 = 2, 6 = 3, 7 = 4 }
delay = 300
threshold = 100
wiegand_pins = { data0 = 2, data1 = 3 }

[event]
event_emitter_name = "SNS" # current valid values are SNS and HTTP, default is SNS if name is not mapped

[event.httpemitter]
post_url = "http://partybeerfuntimez.biz/event" # update with your event collection url